# Generated by Django 2.1.2 on 2018-10-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_level',
        ),
        migrations.AddField(
            model_name='skill',
            name='levels',
            field=models.CharField(choices=[(1, 'Fundamental Awareness'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1, max_length=1),
        ),
    ]
