# Generated by Django 2.1.2 on 2018-10-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181011_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='levels',
            field=models.IntegerField(choices=[(1, 'Fundamental Awareness'), (2, 'Novice'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1),
        ),
    ]
