# Generated by Django 2.1.2 on 2018-10-12 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20181012_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='levels',
            new_name='level',
        ),
    ]
